const express = require('express')
const path = require('path')
const PORT = process.env.PORT || 5000

express()
  .use(express.static(path.join(__dirname, 'public')))
  .set('views', path.join(__dirname, 'views'))
  .set('view engine', 'ejs')
  .get('/', (req, res) => res.render('pages/index'))
  .get('/main_menu',(req, res) => res.render('pages/main_menu'))
  .get('/fetch_student_data',(req, res) => res.render('pages/U4'))
  .get('/classify',(req, res) => res.render('pages/category'))
  .get('/display_student_detail',(req, res) => res.render('pages/display_student_detail'))
  .get('/pass_student_data',(req, res) => res.render('pages/U9'))
  .get('/notice_result',(req, res) => res.render('pages/notice_result'))
  .get('/save_data',(req, res) => res.render('pages/save_data'))
  .get('/noticed',(req, res) => res.render('pages/noticed'))
  .listen(PORT, () => console.log(`Listening on ${ PORT }`))
